### PR TITLE
Adding specific toggle for PVR + Option to enable scene if lights already on without time condition + keep lights off setting

### PR DESCRIPTION
**Pull request by cyberden**
Hello.

I suggest this PR to the main repo.

I added a specific PVR toggle to be able to disable hue actions when using live tv but not "other" content (streaming content for example).

I added an option to activate a scene without schedule/daylight condition if any light of the scene to activate is already "on".

### CODE REVIEW

**Comment by zim514** [comment]
Thanks for submitting this, it's been requested a few times. My Kodi setup is busted so it'll be a while before I can merge it. Did you test it on 18.6?

**Comment by cyberden** [comment]
Tested it on 18.6 but there might be some improvements to make. I will try to work on it tomorrow.

**Comment by cyberden** [comment]
This is better with the third commit. Be careful with the german translation which is direct google translate as I don't speak german at all.

The third commit fixes a bug when stopping live tv where the stop scene was applied even if the setting was "disable for live tv" because of missing filename (as the video is stopped).

It also adds the initial requested setting to keep the lights off. If any of the light of the scene to be applied is off and the setting is set to True, the scene is not applied.

The initial commit was a setting that enabled a scene to be applied outside of the schedule (or in daytime if the setting was ne set) if the any of the light of the scene to be applied is already on. This is useful when you use the daylight setting but the weather is cloudy so you have lights on before sunset and want the lights to dim when you watch something.

Hope it helps and the code is ok. Python is really not my preferred language so feel free to comment.

**Comment by zim514** [comment]
Merged & released
Kept the text strings in English since I don't speak German either

**Pull request merged**
